name: Deploy

on:
    push:
        tags:
            - 'deploy'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Prepare Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'
            - run: npm ci
              name: Install Dependencies
            - run: npm run build
              name: Build
            - name: Publish the Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: dist
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
